language: minimal
cache:
  directories:
    - $HOME/.jabba/

matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      env:
        - JDK="adopt@1.8"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.11"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.13"

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis" 
    
before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../plugin-MyPlugin.zip *; cd ..
  - ant install
  - zip -r Funz-MyPlugin.zip Funz-MyPlugin
  
deploy:
  provider: releases
  api_key:
    secure: __PUT_YOUR_GITHUB_ACCESS_KEY_HERE__:_'travis_setup_releases_--force'_will_generate_a_correct_.travis.yml
  file_glob: true
  file:
    - Funz-*.zip
    - plugin-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
